### ISSUE TITLE
Remove Eliz as maintainer ?

### ISSUE THREAD

**Issue by emdupre** [nipreps/GOVERNANCE#8]
I'm currently listed as a Nipreps maintainer [here](https://github.com/nipreps/GOVERNANCE/blob/main/project-docs/.maint/MAINTAINERS.md), but I don't know that I can devote enough time to this effort to warrant that title !

Just wanted to confirm if I'm supposed to be listed in this capacity ?

**Comment by oesteban** [comment]
There's an HTML comment saying that the names are an example, so it doesn't mean you are a Maintainer.
That said, and truth be told, I used that markdown to debug the script on fMRIPrep, so your name brought up some precious commits.

Anyways, because it is an example, I'll make sure I don't mention anyone there (i.e., replace with J. Doe)

**Comment by emdupre** [comment]
Great, thanks for confirming this !!
